apiVersion: v1
kind: Secret
metadata:
  name: {{ include "hl-leaderboard.name" . }}-secret
  labels:
    {{- include "hl-leaderboard.labels" . | nindent 4 }}
type: Opaque
stringData:
  TELEGRAM_TOKEN: {{ .Values.telegram.token | quote }}
  TELEGRAM_CHAT_ID: {{ .Values.telegram.chatId | quote }}
  LEADERBOARD_ARGS: {{ .Values.leaderboardArgs | quote }}
