---
- name: Install Freqtrade stack on Ubuntu 24.04
  hosts: freqtrade_instances
  become: true
  gather_facts: true

  vars:
    freqtrade_user: freqtrade
    freqtrade_group: freqtrade
    freqtrade_home: /home/freqtrade
    freqtrade_stack_dir: "{{ freqtrade_home }}/stack"
    freqtrade_compose_project_name: freqtrade
    
    # Default versions/images
    freqtrade_base_image: freqtradeorg/freqtrade:stable
    freqtrade_image: freqtrade_custom:latest
    freqtrade_dry_run: true
    
    # bots: {} # Should be provided in env.values.yml

    docker_arch: amd64

  pre_tasks:
    - name: Validate target OS is Ubuntu 24.04
      ansible.builtin.assert:
        that:
          - ansible_facts.distribution == "Ubuntu"
          - ansible_facts.distribution_version is version("24.04", "==")
        fail_msg: "This playbook supports only Ubuntu 24.04 hosts."

  tasks:
    - name: Setup freqtrade user and group
      ansible.builtin.import_tasks: tasks/users.yml

    - name: Install base system packages
      ansible.builtin.import_tasks: tasks/system_packages.yml

    - name: Install and configure Docker
      ansible.builtin.import_tasks: tasks/docker.yml

    - name: Deploy Freqtrade Docker Compose stack
      ansible.builtin.import_tasks: tasks/compose_stack.yml
