livekitHost: "wss://livekit.kuzmentsov.com"

# Must match livekit values.instance.yaml apiKey
livekitKey: "CHANGE_ME"

# Must match livekit values.instance.yaml apiSecret
livekitSecret: "CHANGE_ME"

ingress:
  enabled: true
  className: traefik
  host: "lk-jwt.kuzmentsov.com"
  tls:
    enabled: true
    certManager: "letsencrypt-prod"
    secretName: "lk-jwt-tls"

service:
  type: ClusterIP
