- name: Download Anaconda installer
  ansible.builtin.get_url:
    url: "{{ anaconda_installer_url }}"
    dest: "{{ anaconda_installer_path }}"
    owner: "{{ hummingbot_user }}"
    group: "{{ hummingbot_group }}"
    mode: "0755"

- name: Install Anaconda3 silently if not installed
  ansible.builtin.command:
    cmd: "bash {{ anaconda_installer_path }} -b -p {{ anaconda_install_prefix }}"
    creates: "{{ anaconda_install_prefix }}/bin/conda"
  become_user: "{{ hummingbot_user }}"
