apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "coturn.name" . }}
  labels:
    {{- include "coturn.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "coturn.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "coturn.selectorLabels" . | nindent 8 }}
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/secret.yaml") . | sha256sum }}
    spec:
      containers:
        - name: coturn
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args:
            - -c
            - /etc/coturn/turnserver.conf
          ports:
            - name: turn-tcp
              containerPort: 3478
              protocol: TCP
          volumeMounts:
            - name: config
              mountPath: /etc/coturn/turnserver.conf
              subPath: turnserver.conf
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
        - name: config
          secret:
            secretName: {{ include "coturn.name" . }}-config
            items:
              - key: turnserver.conf
                path: turnserver.conf
