apiVersion: v1
kind: Service
metadata:
  name: {{ include "coturn.name" . }}
  labels:
    {{- include "coturn.labels" . | nindent 4 }}
  annotations:
    {{- toYaml .Values.service.annotations | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "coturn.selectorLabels" . | nindent 4 }}
  ports:
    - name: turn-tcp
      port: 3478
      targetPort: turn-tcp
      protocol: TCP
