apiVersion: v1
kind: Service
metadata:
  name: {{ include "synapse.name" . }}
  labels:
    {{- include "synapse.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    {{- include "synapse.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      port: 8008
      targetPort: http
      protocol: TCP
