apiVersion: v1
kind: Secret
metadata:
  name: {{ include "lk-jwt-service.name" . }}-env
  labels:
    {{- include "lk-jwt-service.labels" . | nindent 4 }}
type: Opaque
stringData:
  LIVEKIT_URL: {{ .Values.livekitHost | quote }}
  LIVEKIT_KEY: {{ .Values.livekitKey | quote }}
  LIVEKIT_SECRET: {{ .Values.livekitSecret | quote }}
