apiVersion: v1
kind: Service
metadata:
  name: {{ include "lk-jwt-service.name" . }}
  labels:
    {{- include "lk-jwt-service.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "lk-jwt-service.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      port: 8080
      targetPort: http
      protocol: TCP
