apiVersion: traefik.io/v1alpha1
kind: IngressRouteTCP
metadata:
  name: {{ include "livekit.name" . }}-rtc
  labels:
    {{- include "livekit.labels" . | nindent 4 }}
spec:
  entryPoints:
    - livekit-tcp
  routes:
    - match: HostSNI(`*`)
      services:
        - name: {{ include "livekit.name" . }}
          port: 7881
---
apiVersion: traefik.io/v1alpha1
kind: IngressRouteTCP
metadata:
  name: {{ include "livekit.name" . }}-turns
  labels:
    {{- include "livekit.labels" . | nindent 4 }}
spec:
  entryPoints:
    - livekit-turns
  routes:
    - match: HostSNI(`*`)
      services:
        - name: {{ include "livekit.name" . }}
          port: 5349
  tls:
    passthrough: true
