apiVersion: v1
kind: Service
metadata:
  name: {{ include "livekit.name" . }}
  labels:
    {{- include "livekit.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "livekit.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      port: 7880
      targetPort: http
      protocol: TCP
    - name: rtc-tcp
      port: 7881
      targetPort: rtc-tcp
      protocol: TCP
    - name: turns
      port: 5349
      targetPort: turns
      protocol: TCP
