apiVersion: v1
kind: Secret
metadata:
  name: {{ include "freqtrade-bot.name" . }}-config
  labels:
    {{- include "freqtrade-bot.labels" . | nindent 4 }}
type: Opaque
stringData:
  config.json: |
    {
      "max_open_trades": {{ .Values.config.maxOpenTrades }},
      "stake_currency": "{{ .Values.config.stakeCurrency }}",
      "stake_amount": {{ .Values.config.stakeAmount }},
      "tradable_balance_ratio": 0.99,
      "amount_reserve_percent": 0.01,
      "available_capital": {{ .Values.config.availableCapital }},
      "dry_run_wallet": 1000.0,
      "dry_run": {{ .Values.config.dryRun }},
      "fee": 0.001,
      "cancel_open_orders_on_exit": true,
      "trading_mode": "{{ .Values.config.tradingMode }}",
      "margin_mode": "{{ .Values.config.marginMode }}",
      "unfilledtimeout": {
        "entry": 15,
        "exit": 15,
        "exit_timeout_count": 10,
        "unit": "seconds"
      },
      "entry_pricing": {
        "price_side": "other",
        "use_order_book": true,
        "order_book_top": 20,
        "price_last_balance": 0.0,
        "check_depth_of_market": {
          "enabled": false,
          "bids_to_ask_delta": 1
        }
      },
      "exit_pricing": {
        "price_side": "other",
        "use_order_book": true,
        "order_book_top": 20
      },
      "exchange": {
        "name": "hyperliquid",
        "walletAddress": "{{ .Values.exchange.walletAddress }}",
        "privateKey": "{{ .Values.exchange.privateKey }}",
        "ccxt_config": {
          "options": { "vaultAddress": "{{ .Values.exchange.vaultAddress }}" },
          "enableRateLimit": true,
          "rateLimit": 1000
        },
        "ccxt_async_config": {
          "enableRateLimit": true,
          "rateLimit": 1000,
          "options": { "vaultAddress": "{{ .Values.exchange.vaultAddress }}" }
        },
        "pair_whitelist": ["BTC/USDC:USDC"],
        "pair_blacklist": []
      },
      "pairlists": [
        {
          "method": "StaticPairList",
          "number_assets": 16,
          "sort_key": "quoteVolume",
          "min_value": 100000,
          "refresh_period": 1800
        }
      ],
      "edge": {
        "enabled": false,
        "process_throttle_secs": 3600,
        "calculate_since_number_of_days": 1500,
        "allowed_risk": 0.01,
        "stoploss_range_min": -0.02,
        "stoploss_range_max": -0.95,
        "stoploss_range_step": -0.001,
        "minimum_winrate": 0.2,
        "minimum_expectancy": 0.1,
        "min_trade_number": 20,
        "max_trade_duration_minute": 28800,
        "remove_pumps": false
      },
      "telegram": {
        "enabled": {{ .Values.telegram.enabled }},
        "token": "{{ .Values.telegram.token }}",
        "chat_id": "{{ .Values.telegram.chatId }}"
      },
      "api_server": {
        "enabled": true,
        "listen_ip_address": "0.0.0.0",
        "listen_port": 8080,
        "verbosity": "info",
        "enable_openapi": false,
        "Force_entry": true,
        "forcebuy_enable": true,
        "force_entry_enable": true,
        "jwt_secret_key": "{{ .Values.api.jwtSecretKey }}",
        "CORS_origins": [],
        "username": "{{ .Values.api.user }}",
        "password": "{{ .Values.api.password }}"
      },
      "buy_params": {
        "LEVERAGE_RATIO": {{ .Values.config.leverageRatio }}
      },
      "bot_name": "{{ include "freqtrade-bot.name" . }}",
      "initial_state": "running",
      "force_entry_enable": true,
      "internals": {
        "process_throttle_secs": 20
      }
    }
