#!/usr/bin/env python3
"""Export the frozen HistGradientBoosting models to a pure-python/numpy form the
bot can evaluate WITHOUT sklearn/pandas (bot image has numpy only). Verifies the
pure evaluator matches sklearn.predict_proba to <1e-9, then writes a compact
base64(gzip(json)) blob as a .py module that ships in the bot ConfigMap."""
import base64, gzip, json, math, pickle, pathlib
import numpy as np, pandas as pd
from train_export import features as pandas_features  # exact training features

COINS = {"btc": "data.csv", "eth": "data_eth.csv", "sol": "data_sol.csv", "xrp": "data_xrp.csv"}
PKL = pathlib.Path("models")


def extract(model):
    base = float(np.ravel(model._baseline_prediction)[0])
    trees = []
    for it in model._predictors:
        n = it[0].nodes
        nodes = [[int(x["is_leaf"]), float(x["value"]), int(x["feature_idx"]),
                  float(x["num_threshold"]), int(x["left"]), int(x["right"]),
                  int(x["missing_go_to_left"])] for x in n]
        trees.append(nodes)
    return base, trees


def eval_tree(nodes, x):
    i = 0
    while not nodes[i][0]:                      # while not leaf
        _, _, fidx, thr, left, right, miss_left = nodes[i]
        xv = x[fidx]
        if xv != xv:                            # NaN
            i = left if miss_left else right
        else:
            i = left if xv <= thr else right
    return nodes[i][1]


def predict_pure(base, trees, x):
    raw = base + sum(eval_tree(t, x) for t in trees)
    return 1.0 / (1.0 + math.exp(-raw))


blob = {}
for coin, path in COINS.items():
    m = pickle.load(open(PKL / f"{coin}_cur2.pkl", "rb"))
    model, feat = m["model"], m["features"]
    base, trees = extract(model)
    # parity check on the whole dataset
    d = pd.read_csv(path)
    for c in ["open","high","low","close","volume","takerBuyBase"]: d[c] = d[c].astype(float)
    X, _ = pandas_features(d)
    X = X[feat].dropna()
    Xv = X.values
    sk = model.predict_proba(Xv)[:, 1]
    pure = np.array([predict_pure(base, trees, Xv[i]) for i in range(len(Xv))])
    md = np.max(np.abs(sk - pure))
    print(f"{coin.upper()} parity: max|sklearn-pure| = {md:.2e}  ({'OK' if md < 1e-9 else 'MISMATCH'})  trees={len(trees)}")
    assert md < 1e-9
    blob[coin] = {"baseline": base, "features": feat, "trees": trees, "horizon": 2}

raw = json.dumps(blob, separators=(",", ":")).encode()
enc = base64.b64encode(gzip.compress(raw, 9)).decode()
out = pathlib.Path("../../src/strategy/_ml_models.py")
out.write_text('"""Auto-generated by backtest/fiftycent/export_pure.py — do not edit.\n'
               'base64(gzip(json)) of the per-coin cur+2 tree ensembles."""\n'
               f"BLOB = {enc!r}\n")
print(f"\nwrote {out}  ({len(enc)} b64 chars, ~{len(enc)//1024}KB; raw json {len(raw)//1024}KB)")
